### PR TITLE
adding phase 3 requirements

### PR DESCRIPTION
**Pull request by monitorjbl**
[Review on Reviewable](https://reviewable.io/reviews/csco-devops-bootcamp/referencerepo/10)

### CODE REVIEW

**Comment by monitorjbl** [comment]
Just FYI, this includes all of the phase 2 requirements. If you want to see what changed for this, only look at r5. As before, the preview is available here: https://preview.c9.io/monitorjbl/referencerepo/app.html

---

Review status: 0 of 5 files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
Reviewed 1 of 5 files at r1, 4 of 4 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
@monitorjbl Looking good. I went ahead and merged these because they do fulfill the requirements. I'm wondering though, if there is any better way to modularize it so that it is easier for the new people in the class. If you think most people will get this pretty easy, then I'm not concerned.

**Comment by monitorjbl** [comment]
Hm, I'm not sure how much to modularize at this point in the project. The general pattern in Angular is to have a single controller per view, so I wouldn't try to break that out. I could move the HTTP call out to an injected service. It would look something like this:

```
app.controller('BlastList', ['$scope', '$http', 'BlastService', function($scope, $http, BlastService) {

  // all the other stuff in the controller...

  BlastService.list().success(function(data) {
    allBlasts = data.records;
    $scope.scroll(0);
  });
}]);

app.factory('BlastService', ['$http', function($http) {
  return {
    list: function() {
      return $http.get('https://raw.githubusercontent.com/CSCO-DevOps-Bootcamp/ReferenceRepo/datafeeds/blastfeed.json');
    }
  }
}]);
```

This would make unit testing possible, but I was worried it might confuse newbies. Thoughts?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
Actually, I think that is the way to go. Will needs to have testable code later for his section so injecting services will help there. Can these be sourced from multiple JS files? One of the reasons why it would be nice to have things more modular is so the people on the teams of 7 can work concurrently.

In terms of app.html, it just seems like some of this could be implemented as template-expanding custom directives to make it more modular: http://plnkr.co/edit/wdSV6aRkXtzKnApzfQp4?p=preview

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by monitorjbl** [comment]
Yeah, you can put them in multiple JS files. How deep do you want to go with that? Each app.foo() call to its own file? Or just one for app/controllers/services?

You can have as many directives as you want, really. The challenge is that the markup stops being readable because you have to read through so many other HTML files and (potentially) lines of JS code. In this case, I wouldn't recommend that every little thing be a directive. At most, you could probably have the title and the buttons be directives, but even then they're very small bits of code that don't seem to be touched in later phases. 

Are you planning on having the attendees work on those other pieces enough to warrant separating them? Or is there something else you had in mind to modularize?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
Each injected service in it's own JS file makes sense to me.

As far as directives, I was thinking the buttons, and the individual blasts, then one directive for the list of blasts. Later on, there should be one for the map of course.

Ideally, I'd like each member of a team to have an opportunity to work on an individual file during each breakout - so that they don't have to do merges. It's okay if their file is only 5 lines long. It's also okay, if for some phases we can only get 2-3 discrete files, where others we get a full 7. It's best-effort really to split it out.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by monitorjbl** [comment]
Sounds good. So, how do you want to implement this change? Are we rewriting the history of the repo to introduce it at the beginning, or do you want to just put it on top of what's in place now?

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
The change need to be applied to all branches. In terms of commit history, we can squash them later if we really want to, so I suggest just leaving the history intact for now.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by monitorjbl** [comment]
We'll lose the common ancestry that way, but that may not be super important if you're not planning on showing the the Git history in detail across branches. I'll open some PRs later this weekend with the updated structure.

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Comment by segfly** [comment]
Yeah, I'm not too worried about that. I can always clean up the history later. I don't want you do more work than necessary, that's for sure. Thanks for the help!

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/10)

**Pull request merged**
