### PR TITLE
adding phase 2 requirements

### PR DESCRIPTION
**Pull request by monitorjbl**
[Review on Reviewable](https://reviewable.io/reviews/csco-devops-bootcamp/referencerepo/8)

### CODE REVIEW

**Comment by monitorjbl** [comment]
So, this is neat. Have you tried out the "Combine commits for review" feature? That would go a long way to making the commit history for Git repos prettier.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by monitorjbl** [comment]
Review status: 0 of 5 files reviewed at latest revision, 2 unresolved discussions, all commit checks successful.

---

<sup>**[.c9/project.settings, line 6 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP19yviFAQhnY2vqTu)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/.c9/project.settings#L6)):</sup>
I went into the settings in Cloud9 and it apparently did this. I don't think I changed anything, but the original settings had everything as strings.

---

<sup>**[blast.html, line 7 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP0s8mQFb7AW4UUvOY)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L7)):</sup>
This is provided in ISO8061 format, but the mockup wants a prettier date format. Should I pull in [moment.js](http://momentjs.com/) and format it, or would you prefer to just update the source JSON?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
@monitorjbl Yep! That's one thing I like about Reviewable.io

**Comment by monitorjbl** [comment]
Review status: 0 of 5 files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[blast.html, line 11 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2SeePdhTj7_s7N08)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L11)):</sup>
Not sure how to get Cloud9's editor to properly add newlines at the end of files, but it would nice if it did that.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
@monitorjbl btw, you can also see/manage issues/PRs on waffle.io
https://waffle.io/CSCO-DevOps-Bootcamp/ReferenceRepo

**Comment by monitorjbl** [comment]
Seems easier to make general comments with GitHub/Waffle than Reviewable. Does Reviewable do much besides let you combine commits? It doesn't seem like it can actually prevent you from merging a PR

**Comment by segfly** [comment]
Reviewable.io supports per-file comments, and allows you to mark files as reviewed/unreviewed. They are going to hook into the GitHub status api so eventually you can block the PR if the review is not completed by a quorum. They just don't have that yet.

Waffle.io on the otherhand supports issues (reviewable does not) and is focuses on treating issues in a kanban fashion.

**Comment by segfly** [comment]
Oh and reviewable.io updates the code you are looking at without having to refresh, if new commits are pushed to the source branch.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[.c9/project.settings, line 6 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP19yviFAQhnY2vqTu)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/.c9/project.settings#L6)):</sup>
That's odd. We'll have to keep an eye on whether this keeps flip-flopping. For now, I'm fine with accepting the changes.

---

<sup>**[app.css, line 0 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2mWtQ3r5-hzGHFz8)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.css#L0)):</sup>
Is this just a stub?

---

<sup>**[app.html, line 14 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP6faZhdMvEy6H_jVJ)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.html#L14)):</sup>
The rough blasts feed look good. This page is however missing a placeholder for the title text. Feel free to take some liberty and make it prettier (though maybe that's why you added app.css?)

---

<sup>**[blast.html, line 7 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP0s8mQFb7AW4UUvOY)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L7)):</sup>
Would it be better to use a date filter?
https://docs.angularjs.org/api/ng/filter/date

---

<sup>**[blast.html, line 11 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2SeePdhTj7_s7N08)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L11)):</sup>
Not sure I understand. Is this something intellij does automatically?
...Just add a hard return at the end of the file before saving..

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by monitorjbl** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

<sup>**[app.css, line 0 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2mWtQ3r5-hzGHFz8)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.css#L0)):</sup>
Yeah, I figured I'd need to do some style updates and I wanted to make sure that they were all done in a single place.

---

<sup>**[app.html, line 14 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP6faZhdMvEy6H_jVJ)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.html#L14)):</sup>
Whoops, had my PDF scrolled down a bit to far. I'll add that in, do you want it to be literally "<Name of Social Media App>" or should I have a sample name? 

---

<sup>**[blast.html, line 7 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP0s8mQFb7AW4UUvOY)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L7)):</sup>
I'd never used the date filter with anything other than a long. Didn't realize it worked with ISO8061 as well,  but I just tried it and it does. Sweet, that makes things easy!

---

<sup>**[blast.html, line 11 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2SeePdhTj7_s7N08)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L11)):</sup>
It's a feature in most desktop IDE formatters. It's easy to add, but really easy to forget or to not notice in code reviews. I think it's one of those conventions from C/C++ that not everyone sticks to, but I like to. It makes certain Bash commands play nicely if you can always count on a newline at the end. Here's an example:

```
cat app.js routes.js
```

If file1 has no newline, then the first line of file2 will be appended to the last line of file1. It's definitely not critical, the biggest issue to most projects is just slightly noisier diffs. If everyone doesn't agree on a standard, tiny, meaningless changes will be cropping up all over the place as different devs submit PRs.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

<sup>**[.c9/project.settings, line 6 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP19yviFAQhnY2vqTu)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/.c9/project.settings#L6)):</sup>
Funny, when I created monitorjbl/ReferenceRepo/#1 the cloud9 added quotes around the tabsize value. I just did git checkout .c9/project.settings to revert it and it stayed.

---

<sup>**[app.html, line 14 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP6faZhdMvEy6H_jVJ)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.html#L14)):</sup>
I think github/reviewable stripped out what it thought was a html tag in your comment. I assume you quoted what was in the PPT deck?

Use the name "Social Media Blaster", unless you can think of something more creative.

---

<sup>**[blast.html, line 7 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP0s8mQFb7AW4UUvOY)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L7)):</sup>
Sweet are you going to push a new commit with it?

---

<sup>**[blast.html, line 11 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP2SeePdhTj7_s7N08)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L11)):</sup>
Ah makes sense. Send C9 a feature request from the support menu. They accommodate things pretty quickly.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
@monitorjbl Hey, I opened a PR against your fork monitorjbl/ReferenceRepo/pull/1 because I pushed the datafeed branches to the master repo. Hopefully you can just accept that and it will update this PR.

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by monitorjbl** [comment]
Review status: 4 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[.c9/project.settings, line 6 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP19yviFAQhnY2vqTu)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/.c9/project.settings#L6)):</sup>
Hm...not sure what that's about then. I did flip one of the settings switches on and then back off, think that might have done it?

---

<sup>**[app.html, line 14 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP6faZhdMvEy6H_jVJ)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.html#L14)):</sup>
MasterBlaster? Anyone that wasted 90 minutes of their life watching Mad Max Beyond Thunderdome will feel slightly vindicated that they got the reference.

---

<sup>**[blast.html, line 7 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP0s8mQFb7AW4UUvOY)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/blast.html#L7)):</sup>
Yep, just waiting on the title question to push.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[app.html, line 14 \[r1\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwP6faZhdMvEy6H_jVJ)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/ba06460a3f37256417aec9a23928535712d97a3d/app.html#L14)):</sup>
I've never seen it - but I plan to watch the remake. :smile: 
Go for it.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by monitorjbl** [comment]
Not sure if there's a more controlled way to do this, but you can see my c9 preview here: https://preview.c9.io/monitorjbl/referencerepo/app.html

---







Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
Reviewed 2 of 2 files at r4.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by segfly** [comment]
I was about to merge this PR this morning, but I saw you had more changes. Did you want to just keep updating this PR until "done" or create multiple PRs?

---

Reviewed 3 of 3 files at r5.
Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[app.js, line 12 \[r5\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwSRFvQpvNDdDXUUUdT)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/db7eaa9d415b34cbbbc43bcdbb1530bbf5305dc7/app.js#L12)):</sup>
Just curious, what does this flag do?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Comment by monitorjbl** [comment]
Mostly a visual fix for what I noticed last night on mobile. I'm good with merging now unless you have other suggestions. 

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[app.js, line 12 \[r5\]](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8#-JwSRFvQpvNDdDXUUUdT)** ([raw file](https://github.com/csco-devops-bootcamp/referencerepo/blob/db7eaa9d415b34cbbbc43bcdbb1530bbf5305dc7/app.js#L12)):</sup>
It replaces the content of the directive tag instead of appending to it. I normally set this to true, just forgot to in the first commits. 

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/csco-devops-bootcamp/referencerepo/8)

**Pull request merged**
